adding subnets and Vnet integration for the appservice module
Nmbrs/terraform-modules pull request #29
Opened 2022-02-01 17:50 UTC by Divyesh85

# Description

Adding Subnet and VNet Resources to app service module and enabling the VNet Integration in the template
# Motivation and Context

# How Has This Been Tested?

I have kept the address space and the address prefix hardcoded for now since i got issue when trying to add it as a variable, was not able to fix it so keeping this for now till i find the solution. 
Please add your comments for any changes needed or something i might have forgotten i will update them.

Ran Locally and tested out. Below is the terraform Plan for the change. 

```

  # module.appservice.azurerm_app_service.app will be created
  + resource "azurerm_app_service" "app" {
      + app_service_plan_id               = (known after apply)
      + app_settings                      = (known after apply)
      + client_affinity_enabled           = false
      + client_cert_enabled               = false
      + client_cert_mode                  = (known after apply)
      + custom_domain_verification_id     = (known after apply)
      + default_site_hostname             = (known after apply)
      + enabled                           = true
      + https_only                        = true
      + id                                = (known after apply)
      + key_vault_reference_identity_id   = (known after apply)
      + location                          = "westeurope"
      + name                              = "as-payroll-test"
      + outbound_ip_address_list          = (known after apply)
      + outbound_ip_addresses             = (known after apply)
      + possible_outbound_ip_address_list = (known after apply)
      + possible_outbound_ip_addresses    = (known after apply)
      + resource_group_name               = "rg-payroll-test"
      + site_credential                   = (known after apply)

      + auth_settings {
          + additional_login_params        = (known after apply)
          + allowed_external_redirect_urls = (known after apply)
          + default_provider               = (known after apply)
          + enabled                        = (known after apply)
          + issuer                         = (known after apply)
          + runtime_version                = (known after apply)
          + token_refresh_extension_hours  = (known after apply)
          + token_store_enabled            = (known after apply)
          + unauthenticated_client_action  = (known after apply)

          + active_directory {
              + allowed_audiences = (known after apply)
              + client_id         = (known after apply)
              + client_secret     = (sensitive value)
            }

          + facebook {
              + app_id       = (known after apply)
              + app_secret   = (sensitive value)
              + oauth_scopes = (known after apply)
            }

          + google {
              + client_id     = (known after apply)
              + client_secret = (sensitive value)
              + oauth_scopes  = (known after apply)
            }

          + microsoft {
              + client_id     = (known after apply)
              + client_secret = (sensitive value)
              + oauth_scopes  = (known after apply)
            }

          + twitter {
              + consumer_key    = (known after apply)
              + consumer_secret = (sensitive value)
            }
        }

      + connection_string {
          + name  = (known after apply)
          + type  = (known after apply)
          + value = (sensitive value)
        }

      + identity {
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = "SystemAssigned"
        }

      + logs {
          + detailed_error_messages_enabled = (known after apply)
          + failed_request_tracing_enabled  = (known after apply)

          + application_logs {
              + file_system_level = (known after apply)

              + azure_blob_storage {
                  + level             = (known after apply)
                  + retention_in_days = (known after apply)
                  + sas_url           = (sensitive value)
                }
            }

          + http_logs {
              + azure_blob_storage {
                  + retention_in_days = (known after apply)
                  + sas_url           = (sensitive value)
                }

              + file_system {
                  + retention_in_days = (known after apply)
                  + retention_in_mb   = (known after apply)
                }
            }
        }

      + site_config {
          + acr_use_managed_identity_credentials = false
          + always_on                            = true
          + dotnet_framework_version             = "v4.0"
          + ftps_state                           = "FtpsOnly"
          + http2_enabled                        = true
          + ip_restriction                       = (known after apply)
          + linux_fx_version                     = (known after apply)
          + local_mysql_enabled                  = (known after apply)
          + managed_pipeline_mode                = "Integrated"
          + min_tls_version                      = (known after apply)
          + number_of_workers                    = (known after apply)
          + remote_debugging_enabled             = false
          + remote_debugging_version             = (known after apply)
          + scm_ip_restriction                   = (known after apply)
          + scm_type                             = (known after apply)
          + scm_use_main_ip_restriction          = false
          + use_32_bit_worker_process            = false
          + vnet_route_all_enabled               = (known after apply)
          + websockets_enabled                   = false
          + windows_fx_version                   = (known after apply)

          + cors {
              + allowed_origins     = (known after apply)
              + support_credentials = (known after apply)
            }
        }

      + source_control {
          + branch             = (known after apply)
          + manual_integration = (known after apply)
          + repo_url           = (known after apply)
          + rollback_enabled   = (known after apply)
          + use_mercurial      = (known after apply)
        }

      + storage_account {
          + access_key   = (sensitive value)
          + account_name = (known after apply)
          + mount_path   = (known after apply)
          + name         = (known after apply)
          + share_name   = (known after apply)
          + type         = (known after apply)
        }
    }

  # module.appservice.azurerm_app_service_plan.app will be created
  + resource "azurerm_app_service_plan" "app" {
      + id                           = (known after apply)
      + kind                         = "Windows"
      + location                     = "westeurope"
      + maximum_elastic_worker_count = (known after apply)
      + maximum_number_of_workers    = (known after apply)
      + name                         = "asp-payroll-test"
      + reserved                     = false
      + resource_group_name          = "rg-payroll-test"

      + sku {
          + capacity = (known after apply)
          + size     = "P1V2"
          + tier     = "PremiumV2"
        }
    }

  # module.appservice.azurerm_app_service_virtual_network_swift_connection.app will be created
  + resource "azurerm_app_service_virtual_network_swift_connection" "app" {
      + app_service_id = (known after apply)
      + id             = (known after apply)
      + subnet_id      = (known after apply)
    }

  # module.appservice.azurerm_application_insights.app will be created
  + resource "azurerm_application_insights" "app" {
      + app_id                                = (known after apply)
      + application_type                      = "web"
      + connection_string                     = (sensitive value)
      + daily_data_cap_in_ [...]

2022-02-01 21:05 UTC, fargozhu commented
@Divyesh85 this will not work for two reasons:

1. we are always trying to create a vnet, even if that is shared between, which will failed for the 2nd time service.
2. reading the terraform warning notes, if we try to create a "new" subnet in an existent vnet, it will overwritte the existent ones.

We may need to rething on the approach and consider the possibility to use the same subnet for all the services in same vnet (one of the options discussed during the planning session).

@pmmluis @filipefigueredo comments are welcome

2022-02-01 21:06 UTC, fargozhu requested changes
Comments added to the pull request conversation.

2022-02-01 22:37 UTC, fargozhu requested changes

2022-02-01 22:37 UTC, fargozhu commented on azure/appservice-windows/main.tf
> +}
```suggestion
data "azurerm_virtual_network" "vnet" {
  name                = var.vnet.name
  resource_group_name = var.vnet.resource_group_name
}
```

2022-02-01 22:37 UTC, fargozhu commented on azure/appservice-windows/main.tf
> +}
A new vnet will be created on each call to this module, and that is not the goal.

2022-02-01 22:37 UTC, fargozhu commented on azure/appservice-windows/main.tf
> +  virtual_network_name = azurerm_virtual_network.app.name
```suggestion
  resource_group_name  = var.vnet.resource_group_name
  virtual_network_name = data.azurerm_virtual_network.vnet.name
```

2022-02-01 22:37 UTC, fargozhu commented on azure/appservice-windows/main.tf
> +    #virtual_network_name      = "${azurerm_virtual_network.vnet.name}"
```suggestion
```

2022-02-01 22:37 UTC, fargozhu commented on azure/appservice-windows/main.tf
> +    #virtual_network_name      = "${azurerm_virtual_network.vnet.name}"
please, no comment code on pull request against main

2022-02-03 08:36 UTC, fargozhu commented
vnet and subnet confguration needs to be supported through nmbrs network template instead of creating through the app service flow.

2022-02-03 10:15 UTC, fargozhu approved these changes

2022-02-03 11:27 UTC, pmmluis approved these changes

2022-02-04 05:50 UTC, merged